name: frip_trading
description: "A new Flutter project."
publish_to: "none"

version: 1.0.5+5

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.7.0
  readmore: ^2.2.0
  flutter_svg: ^2.0.7
  equatable: ^2.0.5
  get_it: ^8.0.1
  intl: any
  dartz: ^0.10.1
  fluro: ^2.0.5
  flutter_bloc: ^9.0.0
  toastification: any
  image_picker: any
  flutter_screenutil: ^5.8.4
  freezed: ^2.4.2
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  lottie: ^3.1.3
  freezed_annotation: ^2.4.4
  # fluttertoast: ^8.2.1
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  # intl_utils: ^2.8.7
  # flutter_localization: any
  # bloc_concurrency: ^0.3.0
  # flutter_animate: ^4.5.2
  # animations: ^2.0.11
  # json_annotation: ^4.8.1
  # cached_network_image: ^3.2.3
  # permission_handler: any
  # internet_connection_checker: ^1.0.0+1
  # shimmer: ^3.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  carousel_slider: ^5.1.1

dev_dependencies:
  # build_runner: ^2.4.13
  # flutter_launcher_icons: ^0.14.3
  # json_serializable: ^6.7.1
  # flutter_native_splash: ^2.4.4

  # fvm dart run dependency_validator
  dependency_validator: ^4.1.3

  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/init_page.png"
  adaptive_icon_background: "#70B9BE"
  min_sdk_android: 21 # android min sdk min:16, default 21

  # web:
  #   generate: true
  #   image_path: "assets/images/init_page.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"

  # windows:
  #   generate: true
  #   image_path: "assets/images/init_page.png"
  #   icon_size: 48 # min:48, max:256, default: 48

  # macos:
  #   generate: true
  #   image_path: "assets/images/init_page.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/SVG/
  fonts:
    - family: Bahij_TheSansArabic
      fonts:
        - asset: assets/fonts/Bahij_TheSansArabic-Bold.ttf
          weight: 500
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf

flutter_intl:
  enabled: true
  class_name: Lang
  main_locale: en_US
  arb_dir: lib/core/localization/l10n
  output_dir: lib/core/localization/generated
